<?php

namespace AppBundle\Repository;

/**
 * OpeningHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHoursRepository extends \Doctrine\ORM\EntityRepository
{
}
